"""initial schema

Revision ID: fe6a72e44a18
Revises: 
Create Date: 2026-09-28 18:11:39.099567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6a72e44a18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('manual', 'csv', 'github', 'hackernews', 'producthunt', 'edgar', 'accelerator', 'job_board', 'web', 'seed', name='sourcekind', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('terms_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'name')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('sub_sector', sa.String(length=100), nullable=True),
    sa.Column('hq_country', sa.String(length=2), nullable=True),
    sa.Column('hq_city', sa.String(length=100), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('stage', sa.Enum('pre_seed', 'seed', 'series_a_plus', 'acquired', 'dead', name='companystage', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('discovered', 'watchlist', 'archived', name='trackingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('accelerator', sa.String(length=100), nullable=True),
    sa.Column('accelerator_batch', sa.String(length=50), nullable=True),
    sa.Column('github_org', sa.String(length=100), nullable=True),
    sa.Column('github_repo', sa.String(length=200), nullable=True),
    sa.Column('hn_launch_item_id', sa.Integer(), nullable=True),
    sa.Column('discovery_source_id', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['discovery_source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_github_org'), ['github_org'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_status'), ['status'], unique=False)

    op.create_table('founder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prior_startups_founded', sa.Integer(), nullable=True),
    sa.Column('prior_exit', sa.Boolean(), nullable=True),
    sa.Column('early_employee_at_scaled_startup', sa.Boolean(), nullable=True),
    sa.Column('domain_years', sa.Float(), nullable=True),
    sa.Column('technical_background', sa.Boolean(), nullable=True),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('publications_count', sa.Integer(), nullable=True),
    sa.Column('notable_employers', sa.JSON(), nullable=True),
    sa.Column('schools', sa.JSON(), nullable=True),
    sa.Column('founder_market_fit_notes', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('domain_years IS NULL OR domain_years >= 0'),
    sa.CheckConstraint('prior_startups_founded IS NULL OR prior_startups_founded >= 0'),
    sa.CheckConstraint('publications_count IS NULL OR publications_count >= 0'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('founder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_founder_name'), ['name'], unique=False)

    op.create_table('company_founder',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('founder_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_cofounder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['founder_id'], ['founder.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'founder_id')
    )
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.Enum('pre_seed', 'seed', 'series_a', 'bridge', 'other', name='roundtype', native_enum=False, length=32), nullable=False),
    sa.Column('instrument', sa.Enum('safe_post', 'safe_pre', 'convertible_note', 'priced_equity', 'unknown', name='instrument', native_enum=False, length=32), nullable=False),
    sa.Column('amount_raised_usd', sa.BigInteger(), nullable=True),
    sa.Column('valuation_cap_usd', sa.BigInteger(), nullable=True),
    sa.Column('cap_type', sa.Enum('post_money', 'pre_money', name='captype', native_enum=False, length=32), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('pre_money_usd', sa.BigInteger(), nullable=True),
    sa.Column('post_money_usd', sa.BigInteger(), nullable=True),
    sa.Column('pro_rata_rights', sa.Boolean(), nullable=True),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('lead_investor', sa.String(length=200), nullable=True),
    sa.Column('investors', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Enum('reported', 'estimated', name='dataconfidence', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_raised_usd IS NULL OR amount_raised_usd > 0'),
    sa.CheckConstraint('discount_rate IS NULL OR (discount_rate >= 0 AND discount_rate < 1)'),
    sa.CheckConstraint('valuation_cap_usd IS NULL OR valuation_cap_usd > 0'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_company_id'), ['company_id'], unique=False)

    op.create_table('signal_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'metric', 'observed_at', 'source_id', name='uq_snapshot_observation')
    )
    with op.batch_alter_table('signal_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_snapshot_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_snapshot_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_snapshot_observed_at'), ['observed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_snapshot_observed_at'))
        batch_op.drop_index(batch_op.f('ix_signal_snapshot_metric'))
        batch_op.drop_index(batch_op.f('ix_signal_snapshot_company_id'))

    op.drop_table('signal_snapshot')
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_company_id'))

    op.drop_table('round')
    op.drop_table('company_founder')
    with op.batch_alter_table('founder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_founder_name'))

    op.drop_table('founder')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_status'))
        batch_op.drop_index(batch_op.f('ix_company_sector'))
        batch_op.drop_index(batch_op.f('ix_company_name'))
        batch_op.drop_index(batch_op.f('ix_company_github_org'))

    op.drop_table('company')
    op.drop_table('source')
    # ### end Alembic commands ###
